"""Initial migration

Revision ID: 3149e5c7288a
Revises: 
Create Date: 2026-07-19 18:14:16.685794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3149e5c7288a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_vjudge_url'), table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_participants_atcoder_handle'), table_name='participants')
    op.drop_index(op.f('ix_participants_codechef_handle'), table_name='participants')
    op.drop_index(op.f('ix_participants_codeforces_handle'), table_name='participants')
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_name'), table_name='participants')
    op.drop_index(op.f('ix_participants_username'), table_name='participants')
    op.drop_index(op.f('ix_participants_vjudge_handle'), table_name='participants')
    op.drop_table('participants')
    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codeforces_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('atcoder_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codechef_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vjudge_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weekly_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contest_solved_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('weekly_contest_solved_problem', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('max_solved_problem', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('weekly_contest_point', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('codeforces_solved_last_7_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('atcoder_solved_last_7_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_solved_last_7_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('codeforces_rating', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('atcoder_rating', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('weekly_positions_history', sa.VARCHAR(length=1000), server_default=sa.text("'[]'::character varying"), autoincrement=False, nullable=True),
    sa.Column('weekly_position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('participants_pkey'))
    )
    op.create_index(op.f('ix_participants_vjudge_handle'), 'participants', ['vjudge_handle'], unique=True)
    op.create_index(op.f('ix_participants_username'), 'participants', ['username'], unique=True)
    op.create_index(op.f('ix_participants_name'), 'participants', ['name'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=True)
    op.create_index(op.f('ix_participants_codeforces_handle'), 'participants', ['codeforces_handle'], unique=True)
    op.create_index(op.f('ix_participants_codechef_handle'), 'participants', ['codechef_handle'], unique=True)
    op.create_index(op.f('ix_participants_atcoder_handle'), 'participants', ['atcoder_handle'], unique=True)
    op.create_table('contests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vjudge_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_rated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), server_default=sa.text('7200'), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contests_pkey'))
    )
    op.create_index(op.f('ix_contests_vjudge_url'), 'contests', ['vjudge_url'], unique=True)
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    # ### end Alembic commands ###
